### PR TITLE
Make @ProfileJvm display the young GC count #71

### PR DESCRIPTION
**Pull request by UbaidurRehman1**
### add display the number of young collections.
- a private method **getYoungGcCount(IItemCollection jfrEvents)** add in **DisplayJvmProfilingValueVerifier** class
- display Young: (number of collections)  below Longest GC pause

### CODE REVIEW

**Comment by UbaidurRehman1** [comment]
Should I close the pull request now?

**Comment by jeanbisutti** [comment]
Thanks for this contribution @UbaidurRehman1!

The PR content is ok for me. I would like to merge this PR on master together with #70.

Are you always intereted in working on #70?

**Comment by UbaidurRehman1** [comment]
Yup I am interested. Assign me #70.

**Comment by jeanbisutti** [comment]
> Should I close the pull request now?

I have just closed the pull request

**Comment by jeanbisutti** [comment]
> Should I close the pull request now?

@UbaidurRehman1 It's ok to keep this PR for the second issue

**Comment by UbaidurRehman1** [comment]
> > Should I close the pull request now?
> 
> @UbaidurRehman1 It's ok to keep this PR for the second issue

Alright

**Comment by UbaidurRehman1** [comment]
@jeanbisutti conflict resolved.

**Comment by jeanbisutti** [comment]
Thanks @UbaidurRehman1.
There are many commits (11).
One would be perfect. The most simple would be to reclone and apply the changes for this issue I think.
Thanks a lot for your contributions and the time you spent to work on QuickPerf.

**Comment by UbaidurRehman1** [comment]
> Thanks @UbaidurRehman1.
> There are many commits (11).
> One would be perfect. The most simple would be to reclone and apply the changes for this issue I think.
> Thanks a lot for your contributions and the time you spent to work on QuickPerf.

So, You want open a new PR?

**Comment by UbaidurRehman1** [comment]
> Thanks @UbaidurRehman1.
> There are many commits (11).
> One would be perfect. The most simple would be to reclone and apply the changes for this issue I think.
> Thanks a lot for your contributions and the time you spent to work on QuickPerf.

Squash is not done cause of their are your commits as well. So, the only option is to re-produce PR for this issue.

**Comment by jeanbisutti** [comment]
@UbaidurRehman1 

> So, You want open a new PR?

Yes, please. The commit history will be cleaner.

Thanks a lot for the time you are spending to work on QuickPerf.

**Comment by jeanbisutti** [comment]
Duplicated with #81

**Pull request closed without merging**
