### PR TITLE
Add @ExpectMaxUpdate #68

### PR DESCRIPTION
**Pull request by FTarfasse**

### CODE REVIEW

**Comment by FTarfasse** [comment]
Hello Jean,

A few thoughts / things :
- New class MaxOfUpdatesPerfIssueVerifier: I noticed after submitting the PR that the mention to N_PLUS_ONE_SELECT made into [HibernateSuggestion](https://github.com/quick-perf/quickperf/blob/master/sql/sql-annotations/src/main/java/org/quickperf/sql/framework/HibernateSuggestion.java) was not the optimal message. I missed the fact that issue #[73] added [N_PLUS_ONE_INSERT](https://github.com/quick-perf/quickperf/pull/73/files) scenario.
So far I didn't find any **recent** forum activity or question about issues on Hibernate batch processing tool and update statements. I'd like to know your opinion on this.

- [JdbcSuggestion](https://github.com/quick-perf/quickperf/blob/master/sql/sql-annotations/src/main/java/org/quickperf/sql/framework/JdbcSuggestion.java): following my first point, this Enum seems tailored for sql statements but as the new / future annotations cover all CRUD operations maybe the alert message should be more generic (or specific) ?

- The test "should_not_fail_if_the_performance_property_is_respected" (already present in [@ExpectMaxSelect test](https://github.com/quick-perf/quickperf/blob/master/sql/sql-integration-test/src/test/java/ExpectMaxSelectTest.java)) passes even though the only code that was written is the annotation ... I'm missing something on this matter ..

Thanks for your feedbacks.

**Comment by jeanbisutti** [comment]
Hello Fabrice,

Sorry for the delay...

Thanks for your PR!

> New class MaxOfUpdatesPerfIssueVerifier: I noticed after submitting the PR that the mention to N_PLUS_ONE_SELECT made into HibernateSuggestion was not the optimal message. I missed the fact that issue #[73] added N_PLUS_ONE_INSERT scenario.
> So far I didn't find any recent forum activity or question about issues on Hibernate batch processing tool and update statements. I'd like to know your opinion on this.

Yes, it's not about N plus one select. A number of UDPATE statements greater than expected could be due to the fact that JDBC batching is unexpectly disabled ([Paper 1](https://abramsm.wordpress.com/2008/04/23/hibernate-batch-processing-why-you-may-not-be-using-it-even-if-you-think-you-are/), [Paper 2](https://stackoverflow.com/questions/27697810/hibernate-disabled-insert-batching-when-using-an-identity-identifier)). In #73, I asked for renaming of  N_PLUS_ONE_INSERT.

> JdbcSuggestion: following my first point, this Enum seems tailored for sql statements but as the new / future annotations cover all CRUD operations maybe the alert message should be more generic (or specific) ?  

I am not sure if I understood. The goal of HibernateSuggestion enum is to provide several types of hibernate hints to fix some classical problems.

> The test "should_not_fail_if_the_performance_property_is_respected" (already present in @ExpectMaxSelect test) passes even though the only code that was written is the annotation ... I'm missing something on this matter ..


 ```java
@RunWith(QuickPerfJUnitRunner.class)
    public static class AClassHavingAMethodAnnotatedWithExpectMaxUpdateAndHavingNoPerfIssue extends SqlTestBase {

        @ExpectMaxUpdate(1)
        @Test
        public void execute_one_update() {
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();
            Query nativeQuery = em.createNativeQuery("UPDATE book SET isbn = :isbn, title = :title WHERE id = :id")
                    .setParameter("isbn", 42)
                    .setParameter("title", "Tristan")
                    .setParameter("id", 40);
            nativeQuery.executeUpdate();
            em.getTransaction().commit();
        }

    }

    @Test
    public void
    should_not_fail_if_the_performance_property_is_respected() {

        // GIVEN
        Class<?> testClass = AClassHavingAMethodAnnotatedWithExpectMaxUpdateAndHavingNoPerfIssue.class;

        // WHEN
        PrintableResult printableResult = PrintableResult.testResult(testClass);

        // THEN
        assertThat(printableResult.failureCount()).isZero();

    }
 ```

`execute_one_update()`  method executes one UPDATE statement and is annotated with `@ExpectMaxUpdate(1)`, so this test method is not supposed to fail.  `should_not_fail_if_the_performance_property_is_respected()` method automatically checks that `execute_one_update()` does not fail.

 Kind regards

Jean

**Comment by FTarfasse** [comment]
Hi Jean,
Thank you for your feedbacks, I will do the corrections you requested. 
Concerning the point on HibernateSuggestion, it is unclear for me what to do for this PR. You mentionned:
> In #73, I asked for renaming of N_PLUS_ONE_INSERT.

Should I wait for issue #73 to be finalized ?

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Thanks a lot.

You can submit a PR without the suggestions. The suggestions could be added later.

Kind regards

**Comment by FTarfasse** [comment]
Hi Jean,

I noticed PR for issue #73 was completed today ! 
Is it ok for you if I wait for the changes done in HibernateSuggestion (BATCHING) to be merged into the master branch ? This way I ll be able to use them and finalize properly this PR in one shot.
Once again, let me know what you think !

Kind regards,

**Comment by jeanbisutti** [comment]
Hi Fabrice,

It would be great!

I would like to merge #73 in a few days. Indeed, I would like to release a new QuickPerf version before.

Is it fine for you to wait for a few days?

Kind regards

**Comment by FTarfasse** [comment]
Absolutely no problem, I'll keep an eye on the repo. Once #73 merged I'll re submit this PR for review :).
Kind regards,

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Thanks for your patience.

A new [PR](https://github.com/quick-perf/quickperf/pull/87) was created to solve #67 issue. This PR was merged.

If you rebase on master, several conficts would probably happen leading to several merges.

The best thing to do could be to create a new PR. Sorry about that.

Kind regards

**Comment by FTarfasse** [comment]
Hi Jean,

I am really (REALLY) sorry, after all the cleaning done locally (rebase from v1, squash etc ...) I forgot to close the old PR before creating the new one ...

I know one Travis check is still in progress but could you give your feedback please ?

Again, sorry for the inconvenience.

Best regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hi Fabrice,

> I am really (REALLY) sorry, after all the cleaning done locally (rebase from v1, squash etc ...) I forgot to close the old PR before creating the new one ...

Perfect!

I checked the PR.  It's all right.

Many thanks for your work Fabrice!

Best regards,

Jean

**Pull request merged**
