### PR TITLE
Upgrade JUnit5 libraries

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by loicmathieu** [comment]
@jeanbisutti there was an unrelated CI issue (TestNG tests seems to be unreliable).
Can you relaunch the CI ?

**Comment by jeanbisutti** [comment]
Done

**Comment by loicmathieu** [comment]
Thanks, CI passes ;)

**Comment by jeanbisutti** [comment]
Thanks for this PR @loicmathieu.  I am not sure about JUnit 5 versions.  I wonder whether `junit-jupiter-engine` and `junit-platform-launcher` should not have a provided scope with a 1.6.0/5.6.0 versions (the minimum versions working with QuickPerf).  In this way, the QuickPerf code will not use JUnit 5 API developed after 1.6.0/5.6.0, and QuickPerf would be compatible with versions equal or greater  1.6.0/5.6.0.

**Comment by loicmathieu** [comment]
This is micro upgrade so it should not be of concern.
JUnit provides new functionalities only on major/minor versions not on micro updates. It follows the semver versionning scheme.

It is best practice to always be on the latests versions on the supported branch (here 5.6) for security concern.

Maybe we should use non-strict versionning (like `[5.6.0,)` or [5.6.0,5.7.0]) but I dont' like it as you didn't know wich version will be resolved.

**Comment by loicmathieu** [comment]
I update the JUnit5 dependencies as provided as we discussed yesterday.

Note that the same should be done for JUnit5 and TestNG for consistency sake.
Note that when it will be included in a release documentation and example needs to be updated.

**Comment by jeanbisutti** [comment]
Thank you @loicmathieu for these code modifications and your remarks

**Comment by jeanbisutti** [comment]
@loicmathieu 

> Note that the same should be done for JUnit5 and TestNG for consistency sake.

The scope is already provided with TestNG:  https://github.com/quick-perf/quickperf/blob/master/testng/testng-listener/pom.xml#L30

**Pull request merged**
