### PR TITLE
Added the possibility to provide a Writer factory through the Measure…

### PR DESCRIPTION
**Pull request by JosePaumard**
…HeapAllocationPerfVerifier.

The allocation informations are then sent to this writer.

It adds an attribute to the MeasureHeapAllocation annotation. 
The Writer factory is modeled by a WriterFactory interface also added. This interface also has a default implementation that wraps System.out. Maybe those two should be moved to a better package. 

Some clumsy tests have been added, as testing what is happenning on System.out is hard.

### CODE REVIEW

**Comment by jeanbisutti** [comment]
Many thanks for this contribution!

**Comment by jeanbisutti** [comment]
QuickPerf supplies `JvmAnnotationBuilder` and `SqlAnnotationBuilder` classes to build and configure [global annotation](https://github.com/quick-perf/doc/wiki/QuickPerf#annotation-scopes).

I suggest to add a constant in `MeasureHeapAllocation` annotation in order not to duplicate the default format value in JvmAnnotationBuilder:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
public @interface MeasureHeapAllocation {

    String DEFAULT_FORMAT = "[QUICK PERF] Measured heap allocation (test method thread): %s\n";
```

`MeasureHeapAllocation` annotation is the first QuickPerf annotation with two members having a default value (the other annotations have at most one member with a default value). Therefore, in order to have a user friendly API and easy to use, we could add four methods in `JvmAnnotationBuilder` to be able to configure a `MeasureHeapAllocation` annotation in several ways and with a global scope:
```java
    public static MeasureHeapAllocation measureHeapAllocation(final String format
                                                            , final Class<? extends WriterFactory> writerFactoryClass) {
        return new MeasureHeapAllocation() {
            @Override
            public String format() {
                return format;
            }

            @Override
            public Class<? extends WriterFactory> writerFactory() {
                return writerFactoryClass;
            }

            @Override
            public Class<? extends Annotation> annotationType() {
                return MeasureHeapAllocation.class;
            }
        };
    }

    public static MeasureHeapAllocation measureHeapAllocation() {
        return measureHeapAllocation(MeasureHeapAllocation.DEFAULT_FORMAT, DefaultWriterFactory.class);
    }

    public static MeasureHeapAllocation measureHeapAllocation(final Class<? extends WriterFactory> writerFactoryClass) {
        return measureHeapAllocation(MeasureHeapAllocation.DEFAULT_FORMAT, writerFactoryClass);
    }

    public static MeasureHeapAllocation measureHeapAllocation(final String format) {
        return measureHeapAllocation(format, DefaultWriterFactory.class);
    }
```

If one day an annotation will have three members with a default value, it could be the time to envision another kind of annotation builder?

What do you think ?

**Comment by jeanbisutti** [comment]
I agree with you that it would be better to move the `WriterFactory` interface and the `DefaultWriterFactory` implemention to another package.

In the future, a `writerFactory` member could be added to other annotations.

I think that the best thing to do would be to add an `org.quickperf.writer` package in the `core` QuickPerf Maven module and to move `WriterFactory` and `DefaultWriterFactory` into this new package.

**Comment by jeanbisutti** [comment]
About the test part, now thanks to the `writerBuilder` parameter, a part of the `@MeasureHeapAllocation` implementation can be automatically checked this way:
```java
package org.quickperf.jvm.allocation;

import org.assertj.core.api.Assertions;
import org.junit.Test;
import org.junit.experimental.results.PrintableResult;
import org.junit.runner.RunWith;
import org.quickperf.junit4.QuickPerfJUnitRunner;
import org.quickperf.jvm.annotations.JvmOptions;
import org.quickperf.jvm.annotations.MeasureHeapAllocation;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;

import static org.assertj.core.api.Assertions.*;
import static org.junit.experimental.results.PrintableResult.testResult;

public class AllocationWriterTest {

    public static final String FILE_PATH = findTargetPath() + "quickperf-allocation-results.txt";

    private static final String findTargetPath() {
        Path targetDirectory = Paths.get("target");
        return targetDirectory.toFile().getAbsolutePath();
    }

    @RunWith(QuickPerfJUnitRunner.class)
    public static class ClassUnderTest {

        @MeasureHeapAllocation(writerFactory = FileWriterBuilder.class, format = "[QUICK PERF LOCAL TEST] Measured heap allocation for ArrayList: %s\n")
        @JvmOptions("-XX:+UseCompressedOops -XX:+UseCompressedClassPointers")
        @Test
        public void allocate_array_list_with_size_100() {
            ArrayList<Object> data = new ArrayList<>(100);
        }

        public static class FileWriterBuilder implements WriterFactory {

            @Override
            public Writer buildWriter() throws IOException {
                return new FileWriter(FILE_PATH);
            }
        }

    }

    @Test public void
    should_write_allocation_measure_into_a_file() {

        // GIVEN
        Class<ClassUnderTest> testClass = ClassUnderTest.class;

        // WHEN
        PrintableResult testResult = testResult(testClass);

        // THEN
        assertThat(testResult.failureCount()).isZero();
        assertThat(new File(FILE_PATH)).hasContent("[QUICK PERF LOCAL TEST] Measured heap allocation for ArrayList: 440.0 bytes");

    }

}

```

Regarding System.out, we could add a Console abstraction that could be overwritten in the test, but I prefer to keep the code simple.

**Comment by JosePaumard** [comment]
New PR on the same feature with a fix for the broken build (I forgot a file in the commit, my bad). 
Also updates as per request: 
- moved WriterFactory and its implementation to a new module / package
- added a constant for the default format

**Comment by jeanbisutti** [comment]
Thanks for these modifications.

Could you please fix the compilation issue on `ClassWithMethodAnnotatedWithMeasureHeapAllocationJUnit4` class?

After that (if the build is OK), could you please squash the commits into one that I could merge?

**Pull request merged**
